[project]
name = "inference"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "async-lru>=2.0.5",
    "fastapi[standard]>=0.121.2",
    "httpx>=0.28.1",
    "sqlalchemy>=2.0.45",
]
