---
# Service: config-service
apiVersion: v1
kind: Service
metadata:
  name: config-service
spec:
  selector:
    app: config-service
  ports:
    - name: local-port
      port: 8000
      targetPort: 8000
      protocol: TCP

---
# Deployment: config-service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-service
spec:
  selector:
    matchLabels:
      app: config-service
  replicas: 1
  template:
    metadata:
      labels:
        app: config-service
    spec:
      containers:
      - name: config-server-container
        image: 172.0.0.39:5000/floodcast-uv-image:latest
        imagePullPolicy: Always
        env:
        - name: SERVICE_NAME
          value: "config-server"
        ports:
        - containerPort: 8000

---
# Service: flow-data-service
apiVersion: v1
kind: Service
metadata:
  name: flow-data-service
spec:
  selector:
    app: flow-data-service
  ports:
    - name: local-port
      port: 8000
      targetPort: 8000
      protocol: TCP

---
# Deployment: flow-data-service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flow-data-service
spec:
  selector:
    matchLabels:
      app: flow-data-service
  replicas: 1
  template:
    metadata:
      labels:
        app: flow-data-service
    spec:
      containers:
      - name: flow-data-container
        image: 172.0.0.39:5000/floodcast-uv-image:latest
        imagePullPolicy: Always
        env:
        - name: SERVICE_NAME
          value: "flow-data"
        ports:
        - containerPort: 8000

---
# Service: gateway-service
apiVersion: v1
kind: Service
metadata:
  name: gateway-service
spec:
  selector:
    app: gateway-service
  ports:
    - name: local-port
      port: 8000
      targetPort: 8000
      protocol: TCP

---
# Deployment: gateway-service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-service
spec:
  selector:
    matchLabels:
      app: gateway-service
  replicas: 1
  template:
    metadata:
      labels:
        app: gateway-service
    spec:
      containers:
      - name: gateway-container
        image: 172.0.0.39:5000/floodcast-uv-image:latest
        imagePullPolicy: Always
        env:
        - name: SERVICE_NAME
          value: "gateway"
        ports:
        - containerPort: 8000

---
# Service: weather-data-service
apiVersion: v1
kind: Service
metadata:
  name: weather-data-service
spec:
  selector:
    app: weather-data-service
  ports:
    - name: local-port
      port: 8000
      targetPort: 8000
      protocol: TCP

---
# Deployment: weather-data-service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-data-service
spec:
  selector:
    matchLabels:
      app: weather-data-service
  replicas: 1
  template:
    metadata:
      labels:
        app: weather-data-service
    spec:
      containers:
        - name: weather-data-container
          image: 172.0.0.39:5000/floodcast-uv-image:latest
          imagePullPolicy: Always
          env:
            - name: SERVICE_NAME
              value: "weather-data"
            - name: METEO_FRANCE_AROME_API_KEY
              valueFrom:
                secretKeyRef:
                  name: meteo-france-arome
                  key: API_KEY
          ports:
            - containerPort: 8000


