---
# Deployment: config-service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-service
spec:
  selector:
    matchLabels:
      app: config-service
  replicas: 1
  template:
    metadata:
      labels:
        app: config-service
    spec:
      containers:
      - name: config-server-container
        image: 172.0.0.39:5000/floodcast-uv-image:latest
        imagePullPolicy: Always
        env:
        - name: SERVICE_NAME
          value: "config-server"
        ports:
        - containerPort: 8000

---
# Deployment: flow-data-service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flow-data-service
spec:
  selector:
    matchLabels:
      app: flow-data-service
  replicas: 1
  template:
    metadata:
      labels:
        app: flow-data-service
    spec:
      containers:
      - name: flow-data-container
        image: 172.0.0.39:5000/floodcast-uv-image:latest
        imagePullPolicy: Always
        env:
        - name: SERVICE_NAME
          value: "flow-data"
        ports:
        - containerPort: 8000

---
# Deployment: gateway-service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-service
spec:
  selector:
    matchLabels:
      app: gateway-service
  replicas: 1
  template:
    metadata:
      labels:
        app: gateway-service
    spec:
      containers:
      - name: gateway-container
        image: 172.0.0.39:5000/floodcast-uv-image:latest
        imagePullPolicy: Always
        env:
        - name: SERVICE_NAME
          value: "gateway"
        ports:
        - containerPort: 8000

---
# Deployment: weather-data-service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-data-service
spec:
  selector:
    matchLabels:
      app: weather-data-service
  replicas: 1
  template:
    metadata:
      labels:
        app: weather-data-service
    spec:
      containers:
      - name: weather-data-container
        image: 172.0.0.39:5000/floodcast-uv-image:latest
        imagePullPolicy: Always
        env:
        - name: SERVICE_NAME
          value: "weather-data"
        ports:
        - containerPort: 8000
