[project]
name = "floodcast"
version = "0.1.0"
description = "Flood prediction microservices."
readme = "README.md"
requires-python = ">=3.13"
dependencies = []

[tool.uv.workspace]
members = ["models/*", "services/*"]
