# Deployment Gateway
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flow-data-service
spec:
  selector:
    matchLabels:
      app: flow-data-service
  replicas: 1
  template:
    metadata:
      labels:
        app: flow-data-service
    spec:
      containers:
      - name: flow-data-container
        image: 172.0.0.39:5000/floodcast-uv-image:latest
        imagePullPolicy: Always
        env:
        - name: SERVICE_NAME
          value: "flow-data"
        ports:
        - containerPort: 8000
