# Deployment Gateway
apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-data-service
spec:
  selector:
    matchLabels:
      app: weather-data-service
  replicas: 1
  template:
    metadata:
      labels:
        app: weather-data-service
    spec:
      containers:
      - name: weather-data-container
        image: 172.0.0.39:5000/floodcast-uv-image:latest
        imagePullPolicy: Always
        env:
        - name: SERVICE_NAME
          value: "weather-data"
        ports:
        - containerPort: 8000
